### PR TITLE
Resolves service provider name

### LINKED ISSUE #35: Incorrect Service Provider name in composer.json
https://github.com/global-devteam/laravel-api-password-reset/blob/06f357edd3fd477a04711358564e1350a16d83e5/composer.json#L31

### PR DESCRIPTION
**Pull request by beauraines**
* fixes file name in composer.json
* minor update to README for new names

closes #35

### CODE REVIEW

**Comment by beauraines** [comment]
This resolves the issues that we were having installing the package fresh this morning.

**Comment by beauraines** [comment]
@cacpmw  what is sider? The links are all unreachable for me?

**Comment by cacpmw** [comment]
@beauraines sider is a free tool for coding style I guess. I didnt have a chance to mess around with it. I guess I will remove it.

Go ahead and merge your fix. We dont need reviews for such small things like this

**Comment by beauraines** [comment]
No need to remove Sider, CI tools are cool. It turns out that the particular hotspot I was using was blocking it.

**Comment by beauraines** [comment]
LOL. I'm still at the hospital after my appointment and it turns out that slider.review is blacklisted by their internet...

**Pull request merged**
